apiVersion: apps/v1
kind: Deployment
metadata:
  name: capgemini-app
  labels:
    app: capgemini-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: capgemini-app
  template:
    metadata:
      labels:
        app: capgemini-app
    spec:
      containers:
        - name: capgemini-app
          image: ayaribechir/devopspfe:latest
          ports:
            - containerPort: 4200
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
---
apiVersion: v1
kind: Service
metadata:
  name: capgemini-service
  labels:
    app: capgemini-app
spec:
  selector:
    app: capgemini-app
  ports:
    - port: 4200
      targetPort: 4200
  type: LoadBalancer
