apiVersion: v1
kind: Service
metadata:
  name: capgemini-service
  labels:
    app: capgemini-app
spec:
  selector:
    app: capgemini-app
  ports:
    - port: 4200
      targetPort: 4200
  type: LoadBalancer
