kind: Deployment
apiVersion: apps/v1
metadata:
   name: capgemini
spec:
   replicas: 2
   selector:      # tells the controller which pods to watch/belong to
    matchLabels:
     app: capgemini
   template:
      metadata:
        labels:
          app: capgemini
      spec:
       containers:
        - name: capgemini
          image: ayaribechir/devopspfe:latest
          command: ["/bin/sh"]
          args: ["-c","sh /usr/local/tomcat/bin/startup.sh;while true; do echo hello; sleep 10;done"]
          imagePullPolicy: Always
          ports:
           - name: http 
             containerPort: 8082