 apiVersion: v1
kind: Service                             
metadata:
  name: capgemini
  labels:
    app: capgemini
spec:
  type: NodePort
  ports:
    - port: 8082
      protocol: TCP
      name: http
  selector:
    app: capgemini                    
                     
